/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmcryptoengine_free: (a: number, b: number) => void;
export const wasmcryptoengine_new: () => number;
export const wasmcryptoengine_generate_nonce: (a: number) => [number, number, number, number];
export const wasmcryptoengine_generate_random_bytes: (a: number, b: number) => [number, number, number, number];
export const wasmcryptoengine_compute_hmac: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const wasmcryptoengine_verify_hmac: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const wasmcryptoengine_encrypt_data: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const wasmcryptoengine_decrypt_data: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const __wbg_wasmvisualengine_free: (a: number, b: number) => void;
export const wasmvisualengine_new: () => number;
export const wasmvisualengine_encode_payload: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const wasmvisualengine_decode_payload: (a: number, b: number, c: number) => [number, number, number, number];
export const __wbg_wasmprotocolengine_free: (a: number, b: number) => void;
export const wasmprotocolengine_new: () => number;
export const wasmprotocolengine_get_state: (a: number) => [number, number];
export const wasmprotocolengine_get_mode: (a: number) => [number, number];
export const wasmprotocolengine_set_mode: (a: number, b: number, c: number) => [number, number];
export const wasmprotocolengine_initiate_handshake: (a: number) => [number, number];
export const wasmprotocolengine_receive_nonce: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmprotocolengine_process_qr_payload: (a: number, b: number, c: number) => [number, number];
export const wasmprotocolengine_receive_ack: (a: number) => [number, number];
export const wasmprotocolengine_send_text_message: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmprotocolengine_receive_message: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmprotocolengine_get_pending_messages: (a: number) => [number, number];
export const wasmprotocolengine_get_session_id: (a: number) => [number, number];
export const wasmprotocolengine_get_public_key: (a: number) => [number, number];
export const wasmprotocolengine_generate_nonce: (a: number) => [number, number];
export const wasmprotocolengine_generate_random_bytes: (a: number, b: number) => [number, number];
export const main: () => void;
export const greet: (a: number, b: number) => [number, number];
export const get_version: () => [number, number];
export const get_build_info: () => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
